version: '3.4'

services:
  rival-politics-core-proxy:
    image: umputun/nginx-le:latest
    container_name: rival-politics-core-proxy
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - /var/lib/docker/volumes/rival-politics-core/_data/etc/ssl:/etc/nginx/ssl
      - ./hub.conf:/etc/nginx/service.conf
      - ./tml-classic/proxy-settings.conf:/etc/nginx/tml-classic/proxy-settings.conf
    environment:
      - TZ=GMT
      - LETSENCRYPT=true
      - LE_EMAIL=dezare3232@gmail.com
      - LE_FQDN=tml-classic.rivalpolitics.ru,rivalpolitics.ru
    networks:
      - rival-politics-core-network

volumes:
  rival-politics-core:
    external: true
    
networks: 
  rival-politics-core-network:
    external: true