version: '3.4'

services:
  rival-politics-core-proxy:
    image: umputun/nginx-le:latest
    container_name: rival-politics-core-proxy
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - /var/lib/docker/volumes/rival-politics-core/_data/etc/ssl:/etc/nginx/ssl
      - ./hub.conf:/etc/nginx/service.conf
      - ./tml-classic/proxy-settings.conf:/etc/nginx/tml-classic/proxy-settings.conf
    environment:
      - TZ=GMT
      - LETSENCRYPT=true
      - LE_EMAIL=dezare3232@gmail.com
      - LE_FQDN=tml-classic.rivalpolitics.ru,rivalpolitics.ru
    networks:
      - rival-politics-core-network

  portainer:
    image: portainer/portainer-ce:latest
    container_name: rival-politics-portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro                                    # Работаем с локальным временем хоста
      - /var/run/docker.sock:/var/run/docker.sock:ro                        # Работаем с сокетом докера
      - /var/lib/docker/volumes/rival-politics-core/_data/portainer-data:/data    # Сохраняем в томе `surfis-volume`
    ports:
      - 9000:9000
  
  pgadmin:
    container_name: rival-politics-pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "9001:80"
    volumes:
      - /var/lib/docker/volumes/rival-politics-core/_data/pgadmin4/servers.json:/pgadmin4/servers.json

volumes:
  rival-politics-core:
    external: true

networks:
  rival-politics-core-network:
    external: true
