name: Deploy Main Service

on:
  push:
    branches: [main]

jobs:
  push_to_docker_hub:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
       
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Test-01
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            bash <(curl -s https://raw.githubusercontent.com/rival-politics/rival-politic/main/service-hub/main-scenario.sh)

# зайти в папку
# Если существует уже запущенный контейнер:
## остановить контейнер
## запушить обновления в buffer папке
## перезаписать данные из buffer в main папку
## запустить docker-compose в main папке
# иначе
## создать buffer папку
## склонировать туда репозиторий
## склонировать данные из buffer в main
## запустить контейнер в main