name: Deploy Main Service

on:
  push:
    branches: [main]

jobs:
  push_to_docker_hub:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
       
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Test-01
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ..
            cd home
            mkdir -p service-hub
            cd service-hub
            git clone https://github.com/rival-politics/rival-politic
            mv ./rival-politic/* .
            rm -rf rival-politic